import Foundation

struct ProjectService {
    static func projects(for profile: StudentProfile, progress: [String: Int]) -> [ScoredProject] {
        projects(for: profile, progress: progress, customProjects: [])
    }

    static func projects(for profile: StudentProfile, progress: [String: Int], customProjects: [Project]) -> [ScoredProject] {
        (catalog + customProjects).map { project in
            ScoredProject(project: project, matchScore: matchScore(for: project, profile: profile), completedMilestones: min(progress[project.id] ?? 0, project.milestones.count))
        }.sorted { lhs, rhs in
            if lhs.isCompleted != rhs.isCompleted { return !lhs.isCompleted }
            return lhs.matchScore > rhs.matchScore
        }
    }

    static func matchScore(for project: Project, profile: StudentProfile) -> Int {
        var score = 50
        score += profile.interests.filter { project.relevantInterests.contains($0) }.count * 7
        score += (profile.strengths + profile.customSkills).filter { project.relevantSkills.contains($0) }.count * 5
        score += profile.careers.filter { project.relevantCareers.contains($0) }.count * 8
        score += profile.fields.filter { project.relevantFields.contains($0) }.count * 8
        if project.sourceRoadmapID != nil { score += 4 }
        return min(max(score, 48), 99)
    }

    static var catalogProjects: [Project] { catalog }

    private static let catalog: [Project] = [
        Project(id: "plant-health-dashboard", title: "Plant Health Dashboard", category: "Data + Biology", goal: "Build a small tool that helps people understand plant health signals.", description: "Combine a real question, a simple data workflow, and a clear interface into a project you can explain and improve.", skills: ["Python", "Research", "Problem solving", "Communication"], milestones: [
            .init(id: "plant-1", title: "Define the question", subtitle: "Choose the plant signal and audience you want to support.", estimatedTime: "45 min"),
            .init(id: "plant-2", title: "Collect and inspect data", subtitle: "Find a small dataset and document what it contains.", estimatedTime: "2–3 hours"),
            .init(id: "plant-3", title: "Build the first version", subtitle: "Create a working analysis or dashboard view.", estimatedTime: "1–2 weeks"),
            .init(id: "plant-4", title: "Document the result", subtitle: "Explain the method, result, and next improvement.", estimatedTime: "1 hour")
        ], resources: ["Python data notebook", "Project README outline", "Data quality checklist"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Science", "Environment", "AI"], relevantSkills: ["Python", "Research", "Problem solving"], relevantCareers: ["AI Researcher", "Biomedical Engineer"], relevantFields: ["Biology", "Computer Science", "Engineering"], sourceRoadmapID: "research-builder"),
        Project(id: "portfolio-site", title: "Personal Portfolio Site", category: "Web + Portfolio", goal: "Create a simple home for your projects, learning, and evidence of growth.", description: "Turn your work into a clear, navigable story that a mentor, program, or college can understand quickly.", skills: ["Programming", "Writing", "Design", "Communication"], milestones: [
            .init(id: "portfolio-site-1", title: "Plan the story", subtitle: "Choose what you want visitors to understand about you.", estimatedTime: "30 min"),
            .init(id: "portfolio-site-2", title: "Build the structure", subtitle: "Create the pages and navigation for your first version.", estimatedTime: "2–4 days"),
            .init(id: "portfolio-site-3", title: "Add project evidence", subtitle: "Write concise case studies for work you actually completed.", estimatedTime: "2–3 days"),
            .init(id: "portfolio-site-4", title: "Publish and review", subtitle: "Share the site and improve it from feedback.", estimatedTime: "1 day")
        ], resources: ["Portfolio case study template", "Accessibility checklist", "Peer feedback prompts"], estimatedCompletion: "1–2 weeks", relevantInterests: ["Technology", "Design", "Writing"], relevantSkills: ["Programming", "Writing", "Creativity", "Communication"], relevantCareers: ["Software Engineer", "Product Designer"], relevantFields: ["Computer Science", "Arts", "Business"], sourceRoadmapID: "portfolio-projects"),
        Project(id: "sensor-study", title: "Sensor Data Mini Study", category: "Research + Engineering", goal: "Use a small sensor dataset to answer a focused question.", description: "Practice the complete research loop: question, evidence, analysis, and a responsible explanation of limits.", skills: ["Research", "Python", "Mathematics", "Writing"], milestones: [
            .init(id: "sensor-1", title: "Choose a measurable question", subtitle: "Define what you want to learn and how you will observe it.", estimatedTime: "1 hour"),
            .init(id: "sensor-2", title: "Prepare the data", subtitle: "Clean and organize the observations for analysis.", estimatedTime: "2–3 hours"),
            .init(id: "sensor-3", title: "Analyze and interpret", subtitle: "Look for patterns without overstating the result.", estimatedTime: "1 week"),
            .init(id: "sensor-4", title: "Share a short report", subtitle: "Communicate the evidence, limits, and next question.", estimatedTime: "2–3 hours")
        ], resources: ["Research question guide", "Data visualization examples", "Short report template"], estimatedCompletion: "1–2 weeks", relevantInterests: ["Engineering", "Science", "AI", "Medicine"], relevantSkills: ["Research", "Python", "Mathematics", "Writing"], relevantCareers: ["AI Researcher", "Biomedical Engineer"], relevantFields: ["Engineering", "Biology", "Medicine"], sourceRoadmapID: "research-builder"),
        Project(id: "community-problem", title: "Community Problem Prototype", category: "Design + Impact", goal: "Design a small response to a problem you see around you.", description: "Work from lived observation to a testable idea, then learn by listening to the people affected.", skills: ["Leadership", "Design", "Communication", "Teamwork"], milestones: [
            .init(id: "community-1", title: "Listen and frame", subtitle: "Learn what the community actually needs before building.", estimatedTime: "1 week"),
            .init(id: "community-2", title: "Sketch a solution", subtitle: "Make the first idea concrete and easy to discuss.", estimatedTime: "2 hours"),
            .init(id: "community-3", title: "Test with feedback", subtitle: "Share a low-cost version and record what you learn.", estimatedTime: "1 week")
        ], resources: ["Interview question prompts", "Prototype planning canvas", "Feedback log"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Entrepreneurship", "Design", "Education", "Environment"], relevantSkills: ["Leadership", "Communication", "Teamwork", "Creativity"], relevantCareers: ["Product Designer"], relevantFields: ["Business", "Psychology", "Arts"], sourceRoadmapID: "portfolio-projects"),
        // MARK: - New Catalog: Software Engineering / CS / AI / Data / Web (12 high-quality ideas)
        Project(id: "ds-visualizer", title: "Data Structures Visualizer", category: "Computer Science + Software", goal: "Build an interactive visualizer for linked lists, stacks, and binary search trees you can demo to peers.", description: "Turn abstract data structures into something you can see and manipulate. Build a small Python or JavaScript tool that lets users insert, delete, and search while watching each step and its time complexity.", skills: ["Data Structures", "Python", "Problem Solving", "Technical Communication"], milestones: [
            .init(id: "ds-vis-1", title: "Design the operations", subtitle: "Choose 3 structures and list the operations and edge cases to support.", estimatedTime: "1 hour"),
            .init(id: "ds-vis-2", title: "Implement clean structures", subtitle: "Code linked list, stack, and BST without UI, with simple tests.", estimatedTime: "1–2 weeks"),
            .init(id: "ds-vis-3", title: "Build interactive view", subtitle: "Render structures with HTML/Canvas or terminal animation and controls.", estimatedTime: "1–2 weeks"),
            .init(id: "ds-vis-4", title: "Document and demo", subtitle: "Write README with examples, complexity table, and a 2-min screen recording.", estimatedTime: "2 hours")
        ], resources: ["VisuAlgo reference", "Python data structures tutorial", "README demo template"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Engineering", "Computer Science", "AI"], relevantSkills: ["Python", "Data Structures", "Problem Solving", "Technical Communication"], relevantCareers: ["Software Engineer", "Software Engineering", "AI Researcher"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "software-engineer"),
        Project(id: "cli-task-manager", title: "CLI Task Manager with Git History", category: "Software Engineering + Tools", goal: "Create a polished command-line task manager that demonstrates disciplined Git workflow.", description: "Build a CLI tool (Python or Node) that lets you add, list, complete, and archive tasks persisted to JSON, with meaningful commits, branches, and a clean Git log you can show.", skills: ["Git", "Version Control Basics", "Software Development", "Project Planning"], milestones: [
            .init(id: "cli-1", title: "Design the CLI", subtitle: "Define commands, flags, and the JSON storage format.", estimatedTime: "1 hour"),
            .init(id: "cli-2", title: "Implement core commands", subtitle: "Build add/list/complete/archive with persistence and input validation.", estimatedTime: "1 week"),
            .init(id: "cli-3", title: "Practice Git workflow", subtitle: "Use branches, meaningful commits, and a pull request for one feature.", estimatedTime: "3–4 days"),
            .init(id: "cli-4", title: "Polish and release", subtitle: "Add help text, README with install steps, and a demo GIF.", estimatedTime: "1 day")
        ], resources: ["GitHub Skills interactive tutorial", "Command-line interface guide", "README template"], estimatedCompletion: "1–2 weeks", relevantInterests: ["Technology", "Engineering", "Computer Science"], relevantSkills: ["Git", "Software Development", "Project Planning", "Version Control"], relevantCareers: ["Software Engineer", "Software Engineering"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "software-engineer"),
        Project(id: "habit-tracker-api", title: "Habit Tracker REST API", category: "Web + API", goal: "Design and ship a well-tested REST API for tracking habits.", description: "From API design to tests, build a Habit Tracker service with endpoints for habits, entries, and streaks. Include unit tests, error handling, and a small frontend or curl demo.", skills: ["APIs", "Unit Testing", "Debugging", "JavaScript", "Software Development"], milestones: [
            .init(id: "habit-api-1", title: "Design the API", subtitle: "Sketch endpoints, status codes, and data model for habits and entries.", estimatedTime: "1 hour"),
            .init(id: "habit-api-2", title: "Build the server", subtitle: "Implement CRUD, validation, and persistence (JSON or SQLite).", estimatedTime: "1–2 weeks"),
            .init(id: "habit-api-3", title: "Write tests and debug", subtitle: "Add unit tests for each endpoint and fix bugs via debugger.", estimatedTime: "1 week"),
            .init(id: "habit-api-4", title: "Document and demo", subtitle: "Publish API docs and a curl/HTTPie demo for reviewers.", estimatedTime: "2 hours")
        ], resources: ["MDN HTTP overview", "REST API design checklist", "Jest/pytest testing guide"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Engineering", "Computer Science"], relevantSkills: ["APIs", "Unit Testing", "Debugging", "Software Development"], relevantCareers: ["Software Engineer", "Software Engineering"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "software-engineer"),
        Project(id: "algo-performance-lab", title: "Algorithm Performance Lab", category: "Computer Science + Data", goal: "Benchmark and visualize sorting and search algorithms to see trade-offs.", description: "Implement classic algorithms (bubble, merge, quick, binary search), measure runtime across input sizes, and build a dashboard that makes the O(n log n) vs O(n²) difference obvious.", skills: ["Data Structures", "Python", "Data Analysis", "Mathematics"], milestones: [
            .init(id: "algo-lab-1", title: "Implement algorithms", subtitle: "Code 4 sorting and 2 search algorithms with correctness checks.", estimatedTime: "1 week"),
            .init(id: "algo-lab-2", title: "Build benchmark harness", subtitle: "Generate inputs and time each algorithm reliably across sizes.", estimatedTime: "3 days"),
            .init(id: "algo-lab-3", title: "Visualize results", subtitle: "Plot time vs n and annotate with big-O expectations.", estimatedTime: "2–3 days"),
            .init(id: "algo-lab-4", title: "Write analysis report", subtitle: "Explain when each algorithm wins and why, with limits.", estimatedTime: "2 hours")
        ], resources: ["Big-O cheat sheet", "Matplotlib tutorial", "Python timeit guide"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Mathematics", "AI", "Computer Science"], relevantSkills: ["Data Structures", "Python", "Data Analysis", "Mathematics"], relevantCareers: ["Software Engineer", "Software Engineering", "AI Researcher"], relevantFields: ["Computer Science", "Mathematics", "Engineering"], sourceRoadmapID: "software-engineer"),
        Project(id: "finance-data-analyzer", title: "Personal Finance Data Analyzer", category: "Data Science + Finance", goal: "Analyze real spending data and answer questions with clear visuals.", description: "Use Python and Pandas to clean a personal or public finance CSV, answer 3 money questions, and publish a short report with 3–5 charts.", skills: ["Python", "Data Analysis", "Statistics", "Technical Communication"], milestones: [
            .init(id: "finance-1", title: "Find and inspect data", subtitle: "Pick a finance CSV (personal export or public) and document its columns.", estimatedTime: "1 hour"),
            .init(id: "finance-2", title: "Clean the dataset", subtitle: "Handle missing values, fix types, and remove duplicates.", estimatedTime: "2–3 hours"),
            .init(id: "finance-3", title: "Analyze and visualize", subtitle: "Answer 3 questions with grouping, averages, and charts.", estimatedTime: "1 week"),
            .init(id: "finance-4", title: "Publish a report", subtitle: "Write findings, limits, and one actionable insight.", estimatedTime: "2 hours")
        ], resources: ["Kaggle Learn Pandas", "Pandas documentation", "Data storytelling guide"], estimatedCompletion: "1–2 weeks", relevantInterests: ["Technology", "Business", "Mathematics"], relevantSkills: ["Python", "Data Analysis", "Statistics", "Technical Communication"], relevantCareers: ["Data Scientist", "Software Engineer", "AI Researcher"], relevantFields: ["Computer Science", "Mathematics", "Business"], sourceRoadmapID: "ai-engineer"),
        Project(id: "campus-faq-chatbot", title: "Campus FAQ Chatbot", category: "AI + Software", goal: "Build a chatbot that answers common campus or school FAQs from real data.", description: "Collect 30–50 real FAQ pairs, try both rule-based and ML approaches (TF-IDF or small LLM), evaluate accuracy, and ship a simple web UI.", skills: ["Python", "Machine Learning", "AI Literacy", "Technical Communication"], milestones: [
            .init(id: "chatbot-1", title: "Collect FAQ data", subtitle: "Gather 30–50 question-answer pairs from your school or community.", estimatedTime: "2 hours"),
            .init(id: "chatbot-2", title: "Build rule-based baseline", subtitle: "Match keywords and respond, measuring baseline accuracy.", estimatedTime: "1 week"),
            .init(id: "chatbot-3", title: "Try ML ranking", subtitle: "Use TF-IDF or embeddings to rank answers and compare to baseline.", estimatedTime: "1 week"),
            .init(id: "chatbot-4", title: "Ship a demo UI", subtitle: "Add a simple Streamlit or web interface and write a short evaluation.", estimatedTime: "1 day")
        ], resources: ["Scikit-learn text tutorial", "Streamlit get-started guide", "Chatbot evaluation checklist"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "AI", "Education"], relevantSkills: ["Python", "Machine Learning", "AI Literacy", "Technical Communication"], relevantCareers: ["AI Researcher", "Software Engineer", "Software Engineering"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "ai-engineer"),
        Project(id: "image-classifier-pets", title: "Image Classifier — Pets vs Wildlife", category: "AI + Data", goal: "Train an image classifier and evaluate it responsibly with a confusion matrix.", description: "Build a pets-vs-wildlife classifier using a small public dataset (or your own photos). Compare two models, handle overfitting, and publish a model card explaining performance and limits.", skills: ["Machine Learning", "Model Evaluation", "Python", "Data Analysis"], milestones: [
            .init(id: "img-cls-1", title: "Prepare the dataset", subtitle: "Collect or download labeled images and split train/test cleanly.", estimatedTime: "2–3 hours"),
            .init(id: "img-cls-2", title: "Train two models", subtitle: "Try a simple baseline and one stronger model (transfer or CNN).", estimatedTime: "1–2 weeks"),
            .init(id: "img-cls-3", title: "Evaluate responsibly", subtitle: "Report accuracy, precision/recall, and a confusion matrix.", estimatedTime: "1 day"),
            .init(id: "img-cls-4", title: "Publish model card", subtitle: "Share a one-page card with results, limits, and next steps.", estimatedTime: "2 hours")
        ], resources: ["Google ML Crash Course", "Teachable Machine guide", "Scikit-learn image tutorial"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "AI", "Science"], relevantSkills: ["Machine Learning", "Model Evaluation", "Python", "Data Analysis"], relevantCareers: ["AI Researcher", "Data Scientist"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "ai-engineer"),
        Project(id: "markdown-notes-app", title: "Local-First Markdown Notes App", category: "Web + Productivity", goal: "Ship a fast, offline Markdown notes app you actually use daily.", description: "Create a local-first notes app that edits Markdown, previews live, saves to localStorage/files, and supports search and tags. No backend needed — works offline.", skills: ["Web Development", "JavaScript", "Writing", "Design"], milestones: [
            .init(id: "notes-app-1", title: "Design the experience", subtitle: "Sketch editor, preview, and search flows with accessibility in mind.", estimatedTime: "1 hour"),
            .init(id: "notes-app-2", title: "Build editor + preview", subtitle: "Implement Markdown parsing, live preview, and file save/load.", estimatedTime: "1–2 weeks"),
            .init(id: "notes-app-3", title: "Add search and tags", subtitle: "Make notes findable with search, tags, and keyboard shortcuts.", estimatedTime: "1 week"),
            .init(id: "notes-app-4", title: "Polish and publish", subtitle: "Test offline use, write README, and deploy to GitHub Pages.", estimatedTime: "1 day")
        ], resources: ["MDN Web Docs", "GitHub Pages guide", "Markdown guide"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Design", "Writing", "Computer Science"], relevantSkills: ["Web Development", "JavaScript", "Writing", "Design"], relevantCareers: ["Software Engineer", "Software Engineering", "Product Designer"], relevantFields: ["Computer Science", "Arts"], sourceRoadmapID: "portfolio-projects"),
        Project(id: "open-source-sprint", title: "Open-Source Good First Issue Sprint", category: "Collaboration + Software", goal: "Ship two pull requests to beginner-friendly open-source projects.", description: "Find 'good first issue' tickets, set up the repos, make focused changes with tests, and get feedback from maintainers. Document what contribution taught you.", skills: ["Git", "Collaboration", "Documentation", "Software Development"], milestones: [
            .init(id: "oss-1", title: "Find good issues", subtitle: "Pick 2 repos and 2 labeled 'good first issue' tasks you can finish.", estimatedTime: "2 hours"),
            .init(id: "oss-2", title: "Ship first PR", subtitle: "Fork, branch, code, test, and open a pull request with clear description.", estimatedTime: "1 week"),
            .init(id: "oss-3", title: "Ship second PR", subtitle: "Repeat with a different repo or language, incorporating feedback.", estimatedTime: "1 week"),
            .init(id: "oss-4", title: "Reflect and share", subtitle: "Write a short post about what you learned collaborating in the open.", estimatedTime: "2 hours")
        ], resources: ["GitHub Skills", "How to find good first issues", "Pull request template guide"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Engineering", "Computer Science"], relevantSkills: ["Git", "Collaboration", "Documentation", "Software Development"], relevantCareers: ["Software Engineer", "Software Engineering"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "software-engineer"),
        Project(id: "job-market-scraper", title: "Job Market Web Scraper & Dashboard", category: "Data + Web", goal: "Scrape public job listings and reveal trends in skills and locations.", description: "Build a respectful scraper (or use a public dataset), clean titles and skills, and visualize what technologies and locations appear most — with notes on sampling limits.", skills: ["Python", "Data Collection", "Data Analysis", "Research"], milestones: [
            .init(id: "scraper-1", title: "Plan respectful collection", subtitle: "Check terms, rate limits, and decide on dataset vs live scrape.", estimatedTime: "1 hour"),
            .init(id: "scraper-2", title: "Collect and clean", subtitle: "Gather 200+ postings or use a sample CSV and normalize fields.", estimatedTime: "1 week"),
            .init(id: "scraper-3", title: "Analyze and visualize", subtitle: "Chart top skills, locations, and trends with 3–5 visuals.", estimatedTime: "1 week"),
            .init(id: "scraper-4", title: "Publish insights", subtitle: "Share a report with methods, limits, and one career takeaway.", estimatedTime: "2 hours")
        ], resources: ["Beautiful Soup docs", "Pandas data cleaning guide", "Data visualization examples"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Business", "Engineering"], relevantSkills: ["Python", "Data Collection", "Data Analysis", "Research"], relevantCareers: ["Data Scientist", "Software Engineer", "AI Researcher"], relevantFields: ["Computer Science", "Business", "Engineering"], sourceRoadmapID: "research-builder"),
        Project(id: "debug-legacy-codebase", title: "Debug & Test Legacy Codebase", category: "Software Quality + Engineering", goal: "Rescue a buggy codebase by reproducing issues, fixing them, and adding tests.", description: "Take a small intentionally buggy app, reproduce 5 bugs, fix them with the debugger (not prints), and add unit tests so they never return.", skills: ["Debugging", "Unit Testing", "Quality Assurance", "Software Development"], milestones: [
            .init(id: "debug-1", title: "Reproduce the bugs", subtitle: "List 5 bugs, write steps to reproduce each consistently.", estimatedTime: "2 hours"),
            .init(id: "debug-2", title: "Fix with debugger", subtitle: "Use breakpoints and step-through to locate and fix each cause.", estimatedTime: "1 week"),
            .init(id: "debug-3", title: "Add unit tests", subtitle: "Write 8–10 tests that would have caught the bugs.", estimatedTime: "1 week"),
            .init(id: "debug-4", title: "Document quality", subtitle: "Write a short quality log with bug, cause, fix, and prevention.", estimatedTime: "2 hours")
        ], resources: ["VS Code debugging guide", "pytest/Jest tutorial", "Bug report template"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Engineering", "Computer Science"], relevantSkills: ["Debugging", "Unit Testing", "Quality Assurance", "Software Development"], relevantCareers: ["Software Engineer", "Software Engineering"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "software-engineer"),
        Project(id: "accessibility-auditor", title: "Accessibility Auditor Browser Extension", category: "Web + Impact", goal: "Build a browser extension that audits any page for basic accessibility issues.", description: "Create an extension that checks headings, alt text, contrast hints, and form labels, then shows a simple report with fixes. Test it on real sites you use.", skills: ["Web Development", "Quality Assurance", "Technical Writing", "Empathy"], milestones: [
            .init(id: "a11y-1", title: "Learn accessibility basics", subtitle: "Study WCAG quick reference and pick 5 checks to automate.", estimatedTime: "2 hours"),
            .init(id: "a11y-2", title: "Build the extension", subtitle: "Inject a content script, run checks, and show a popup report.", estimatedTime: "1–2 weeks"),
            .init(id: "a11y-3", title: "Test on real sites", subtitle: "Audit 5 sites, log issues, and refine messages to be actionable.", estimatedTime: "1 week"),
            .init(id: "a11y-4", title: "Publish and share", subtitle: "Write install instructions and share with a teacher or peer for feedback.", estimatedTime: "1 day")
        ], resources: ["WCAG quick reference", "Chrome Extensions docs", "Axe accessibility guide"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Design", "Education"], relevantSkills: ["Web Development", "Quality Assurance", "Technical Writing", "Communication"], relevantCareers: ["Software Engineer", "Product Designer"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "portfolio-projects"),
        Project(id: "secure-password-vault", title: "Secure Password Vault", category: "Security + Software", goal: "Build a local, encrypted password vault with a focus on safe design decisions.", description: "Build a CLI or small web vault that encrypts passwords locally, generates strong passwords, and explains your threat model and the limits of your approach — all with free, offline tools.", skills: ["Python", "Problem Solving", "Critical Thinking", "Documentation"], milestones: [
            .init(id: "vault-1", title: "Design the threat model", subtitle: "Decide what you protect against and what you explicitly do not.", estimatedTime: "1 hour"),
            .init(id: "vault-2", title: "Build encrypted storage", subtitle: "Implement add/get with local encryption and master password hashing.", estimatedTime: "1–2 weeks"),
            .init(id: "vault-3", title: "Add generator and checks", subtitle: "Create a strong generator and rate your passwords with transparent rules.", estimatedTime: "1 week"),
            .init(id: "vault-4", title: "Document security", subtitle: "Write a README covering usage, risks, and how you would improve it.", estimatedTime: "2 hours")
        ], resources: ["OWASP password guide", "Python cryptography docs", "README security template"], estimatedCompletion: "2–3 weeks", relevantInterests: ["Technology", "Engineering", "Computer Science"], relevantSkills: ["Python", "Problem Solving", "Critical Thinking", "Documentation"], relevantCareers: ["Software Engineer", "Software Engineering", "Cybersecurity"], relevantFields: ["Computer Science", "Engineering"], sourceRoadmapID: "software-engineer")
    ]
}
